### ISSUE TITLE
Body Parser dan Express

### ISSUE THREAD

**Issue by daudfauzy98** [wskurniawan/dts-database-2#2]
Mas, bedanya `app.use(express.json())` dengan `app.use(body-parser.json())` apa ya?

**Comment by wskurniawan** [comment]
Seteleah kubaca di dokumentasi, ternyata sejak express v 4, parse request body json udah dibalikin lagi ke express, jadi sekarang bisa langsung pakai aja express.json() tanpa import body-parser
